Repository DOSOPT-CDS-TABLING/Tabling-Server, pull requests merged in 2023-11, with the labels that each got.

#2 feat: 매장 리스트 반환 API 개발
  src/main/java/org/sopt/tablingServer/common/exception/model/ErrorType.java
  src/main/java/org/sopt/tablingServer/common/exception/model/SuccessType.java
  src/main/java/org/sopt/tablingServer/shop/ShopController.java
  src/main/java/org/sopt/tablingServer/shop/ShopService.java
  src/main/java/org/sopt/tablingServer/shop/dto/response/ShopResponse.java
  src/main/java/org/sopt/tablingServer/shop/infrastructure/ShopJpaRepository.java
Labels: 동섭🍦, 🪄API, ✨Feat, 🔥 Pull Request

#5 feat: 매장 상세 정보 반환 API 개발
  src/main/java/org/sopt/tablingServer/common/exception/model/ErrorType.java
  src/main/java/org/sopt/tablingServer/common/exception/model/SuccessType.java
  src/main/java/org/sopt/tablingServer/shop/ShopController.java
  src/main/java/org/sopt/tablingServer/shop/ShopService.java
  src/main/java/org/sopt/tablingServer/shop/domain/Menu.java
  src/main/java/org/sopt/tablingServer/shop/domain/Review.java
  src/main/java/org/sopt/tablingServer/shop/dto/response/MenuInfoResponse.java
  src/main/java/org/sopt/tablingServer/shop/dto/response/MenuResponse.java
  src/main/java/org/sopt/tablingServer/shop/dto/response/ReviewResponse.java
  src/main/java/org/sopt/tablingServer/shop/dto/response/ShopDetailResponse.java
  src/main/java/org/sopt/tablingServer/shop/infrastructure/ShopJpaRepository.java
Labels: 동섭🍦, 🪄API, ☁️Database, ✨Feat, 🔥 Pull Request

#7 feat: 이용예정/완료된 주문내역 목록을 출력하는 API 개발
  .gitignore
  src/main/java/org/sopt/tablingServer/common/exception/model/ErrorType.java
  src/main/java/org/sopt/tablingServer/common/exception/model/SuccessType.java
  src/main/java/org/sopt/tablingServer/order/application/OrderService.java
  src/main/java/org/sopt/tablingServer/order/domain/Order.java
  src/main/java/org/sopt/tablingServer/order/dto/response/OrderDetailResponse.java
  src/main/java/org/sopt/tablingServer/order/dto/response/OrderListResponse.java
  src/main/java/org/sopt/tablingServer/order/infrastructure/OrderJpaRepository.java
  src/main/java/org/sopt/tablingServer/order/presentation/OrderController.java
Labels: 승환🍪, 🪄API, ✨Feat, 🔥 Pull Request

#11 feat: 확정 코드를 입력하여 이용예정을 이용완료로 바꾸는 API 개발
  src/main/java/org/sopt/tablingServer/order/controller/OrderController.java
  src/main/java/org/sopt/tablingServer/order/service/OrderService.java
Labels: 승환🍪, 🪄API, ✨Feat, 🧵Git, 🔥 Pull Request

#12 feat: 확정 코드를 입력하여 이용예정을 이용완료로 바꾸는 API 개발
  src/main/java/org/sopt/tablingServer/common/exception/model/ErrorType.java
  src/main/java/org/sopt/tablingServer/common/exception/model/SuccessType.java
  src/main/java/org/sopt/tablingServer/order/controller/OrderController.java
  src/main/java/org/sopt/tablingServer/order/domain/Order.java
  src/main/java/org/sopt/tablingServer/order/dto/request/OrderCompleteRequest.java
  src/main/java/org/sopt/tablingServer/order/dto/response/OrderCompleteResponse.java
  src/main/java/org/sopt/tablingServer/order/service/OrderService.java
Labels: 승환🍪, 🪄API, 🧹Chore, ✨Feat

#15 refactor: 코드리뷰 사항 적용
  .gitignore
  build.gradle
  src/main/java/org/sopt/tablingServer/common/exception/GlobalExceptionHandler.java
  src/main/java/org/sopt/tablingServer/common/exception/model/ErrorType.java
  src/main/java/org/sopt/tablingServer/order/controller/OrderController.java
  src/main/java/org/sopt/tablingServer/order/dto/request/OrderReserveRequest.java
  src/main/java/org/sopt/tablingServer/order/service/OrderService.java
  src/main/java/org/sopt/tablingServer/shop/controller/ShopController.java
  src/main/java/org/sopt/tablingServer/shop/dto/response/shop/ShopDetailResponse.java
  src/main/java/org/sopt/tablingServer/shop/service/ShopService.java
  src/main/resources/application.yml
Labels: 동섭🍦, 🧹Chore, 🚀Deploy, 🔥 Pull Request, 🔨Refactor

#17 chore: 배포를 위한 추가 설정
  src/main/java/org/sopt/tablingServer/common/constant/Constraint.java
  src/main/java/org/sopt/tablingServer/order/controller/OrderController.java
  src/main/java/org/sopt/tablingServer/order/dto/response/OrderCompleteResponse.java
  src/main/java/org/sopt/tablingServer/order/dto/response/OrderDetailResponse.java
  src/main/java/org/sopt/tablingServer/order/dto/response/OrderListResponse.java
  src/main/java/org/sopt/tablingServer/order/service/OrderService.java
  src/main/java/org/sopt/tablingServer/shop/controller/ShopController.java
  src/main/java/org/sopt/tablingServer/shop/service/ShopService.java
  src/main/resources/application.yml
Labels: 동섭🍦, 🧹Chore, 🚀Deploy, 🔧Modify, 🔥 Pull Request, 🔨Refactor
